/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function WorkRoom(props) {
  const { nodes, materials } = useGLTF('models/working_room.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.desk}
        position={[-0.722, -0.003, 0.091]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.desk}
        position={[-0.722, 0, 0.091]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.desk}
        position={[-0.722, -0.003, 0.086]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.desk}
        position={[-0.722, -0.003, 0.091]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.desk}
        position={[-0.722, 0, 0.091]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.desk}
        position={[-0.722, -0.003, 0.091]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.desk}
        position={[-0.722, 0, 0.091]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <group position={[-0.722, 0, 0.091]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials.desktop}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials['Image to Hologram (Generator)']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rubic.geometry}
        material={nodes.rubic.material}
        position={[-0.669, 0.306, 0.558]}
        rotation={[-Math.PI, 1.194, -Math.PI]}
        scale={0.006}
      />
      <group
        position={[-0.017, 0.419, 0.678]}
        rotation={[-Math.PI, 0.735, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials.gameboy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials.right}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_3.geometry}
          material={materials.left}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_4.geometry}
          material={materials.top}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_5.geometry}
          material={materials.bottom}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_6.geometry}
          material={materials.controll}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[0.014, 0.418, 0.694]}
        rotation={[-Math.PI, 0.735, -Math.PI]}
      />
      <group
        position={[-0.687, 0.417, 0.822]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.298, 0.298, 0.39]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials.paper}
        />
      </group>
      <group
        position={[-0.687, 0.43, 0.822]}
        rotation={[Math.PI, -0.154, Math.PI]}
        scale={[0.277, 0.277, 0.362]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.paper}
        />
      </group>
      <group
        position={[-0.687, 0.443, 0.822]}
        rotation={[Math.PI, -0.085, Math.PI]}
        scale={[0.277, 0.277, 0.362]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials.paper}
        />
      </group>
      <group
        position={[-0.651, 0.211, 0.59]}
        rotation={[-Math.PI, 0.015, -Math.PI]}
        scale={[0.298, 0.298, 0.39]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_2.geometry}
          material={materials.paper}
        />
      </group>
      <group
        position={[-0.651, 0.225, 0.59]}
        rotation={[-Math.PI, 0.015, -Math.PI]}
        scale={[0.298, 0.298, 0.39]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials.paper}
        />
      </group>
      <group
        position={[-0.651, 0.24, 0.59]}
        rotation={[-Math.PI, 0.015, -Math.PI]}
        scale={[0.298, 0.298, 0.39]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials.paper}
        />
      </group>
      <group
        position={[-0.651, 0.254, 0.59]}
        rotation={[-Math.PI, 0.015, -Math.PI]}
        scale={[0.298, 0.298, 0.39]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_2.geometry}
          material={materials.paper}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.keyboard}
        position={[-0.36, 0.413, 0.712]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.keyboard}
        position={[-0.559, 0.413, 0.673]}
        rotation={[0, 1.09, -Math.PI]}
        scale={[-1, -1, -0.392]}
      />
      <group
        position={[0.06, 0.466, 0.782]}
        rotation={[-Math.PI, 0.009, -Math.PI]}
        scale={0.068}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials.lamp}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.bed}
        position={[0.963, 0.094, 0.373]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials.bed}
        position={[0.963, 0.347, 0.963]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.bed}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials.bed}
        position={[1.283, 0.456, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials.bed}
        position={[1.151, 0.274, 0.811]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.bed}
        position={[0.837, 0.356, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.bed}
        position={[1.107, 0.356, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.bed}
        position={[0.97, 0.456, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials.bed}
        position={[0.597, 0.356, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials.bed}
        position={[1.337, 0.356, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials.bed}
        position={[1.283, 0.256, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials.bed}
        position={[0.649, 0.256, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.bed}
        position={[0.97, 0.256, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.bed}
        position={[0.757, 0.274, 0.811]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.bed}
        position={[0.65, 0.456, 0.959]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.woods}
        position={[0.123, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials.carpet}
        position={[0.917, 0.009, -0.724]}
        scale={[1, 0.15, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials.desktop}
        position={[-0.867, 0.798, 0.586]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials.desktop}
        position={[-0.867, 0.798, 0.353]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials.desktop}
        position={[-0.867, 0.798, 0.815]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials.desktop}
        position={[-0.867, 0.644, 0.586]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials.desktop}
        position={[-0.867, 0.644, 0.353]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials.desktop}
        position={[-0.867, 0.644, 0.815]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials.sofa}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials.sofa}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials.sofa}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.tv}
        position={[-0.834, 0.35, -0.687]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.709}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials.sofa}
        position={[-0.703, 0.068, -0.687]}
        scale={[1, 0.628, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_1.geometry}
        material={materials.wall}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_2.geometry}
        material={materials.carpet}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_3.geometry}
        material={materials.wall2}
      />
    </group>
  );
}

useGLTF.preload('models/working_room.glb');
